"""add_docs_pr_number_to_drift_events

Revision ID: 0bc81fd23c89
Revises: fac74805b340
Create Date: 2026-03-08 21:37:36.235791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bc81fd23c89'
down_revision = 'fac74805b340'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drift_events', sa.Column('docs_pr_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drift_events', 'docs_pr_number')
    # ### end Alembic commands ###
