"""Add is_suspended and rename to repo_name

Revision ID: 2331b7d24e6e
Revises: 2b0425238d1b
Create Date: 2026-01-31 12:53:39.651526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2331b7d24e6e'
down_revision = '2b0425238d1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('repo_name', sa.String(), nullable=False))
    op.add_column('repositories', sa.Column('is_suspended', sa.Boolean(), nullable=True))
    op.drop_constraint(op.f('repositories_installation_id_full_name_key'), 'repositories', type_='unique')
    op.create_unique_constraint(None, 'repositories', ['installation_id', 'repo_name'])
    op.drop_column('repositories', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'repositories', type_='unique')
    op.create_unique_constraint(op.f('repositories_installation_id_full_name_key'), 'repositories', ['installation_id', 'full_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('repositories', 'is_suspended')
    op.drop_column('repositories', 'repo_name')
    # ### end Alembic commands ###
