"""Add GH username

Revision ID: 273615609168
Revises: 9548114dcc63
Create Date: 2026-01-31 00:54:05.416824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '273615609168'
down_revision = '9548114dcc63'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'github_username')
    # ### end Alembic commands ###
