"""cascade delete repos and avatar_url moved

Revision ID: 2b0425238d1b
Revises: 273615609168
Create Date: 2026-01-31 11:00:07.271295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b0425238d1b'
down_revision = '273615609168'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('avatar_url', sa.String(), nullable=True))
    op.drop_constraint(op.f('repositories_installation_id_fkey'), 'repositories', type_='foreignkey')
    op.create_foreign_key(None, 'repositories', 'installations', ['installation_id'], ['installation_id'], ondelete='CASCADE')
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'repositories', type_='foreignkey')
    op.create_foreign_key(op.f('repositories_installation_id_fkey'), 'repositories', 'installations', ['installation_id'], ['installation_id'])
    op.drop_column('repositories', 'avatar_url')
    # ### end Alembic commands ###
